### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by funnyboy-roks** [funnyboy-roks/worldedit-selection-viewer#33]
Add a yaml config file that has some default settings

```yml
default-color: yellow
default-visibility: holding-tool

refresh-rate: 2 # May want to do some conversions so it's not just a number?
step-size: 0.1
optimise-lines: false
```
